### ISSUE TITLE
Practica Conjuntos Elisa, Diego E y Nestor

### ISSUE THREAD

**Issue by elisa1223** [SistemasTecTlaxiaco/actividad-5-practica-de-conjuntos-equipo-nestor-diego-elisa#1]
[OPERACIONES_CON_CONJUNTOS EQUIPO ELISA 1AS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-practica-de-conjuntos-equipo-nestor-diego-elisa/files/12772373/OPERACIONES_CON_CONJUNTOS.EQUIPO.ELISA.1AS.pdf)

**Comment by josealfredo79** [comment]
Calificacion..????

**Comment by NBbrook** [comment]
Portada: 25%
Procedimiento: 25 %
Figuras: 25%
Resultados: 25% 
Total 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
